wip

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -7,12 +7,30 @@ echo
 
 file=$(<target/checkstyle-result.xml)
 
-if [[ "$file" == *"<error"* ]]; then
-  echo "There are linting errors. Please check the report (target/site/checkstyle.html)"
-  echo
-  exit 1
-else
-  echo "No linting errors"
-  echo
-  exit 0
-fi
+
+input="target/checkstyle-result.xml"
+while IFS= read -r line
+do
+  if [[ "$line" == *"<error"* ]]; then
+  	echo "+++++++++++++++++++++++++++++++++++++++++++++"
+  	endSubstring=$(awk -v a="$line" -v b=" source" 'BEGIN{print index(a,b)}')
+  	# awk -v a="$line" -v b="puppycrawl" 'BEGIN{print index(a,b)}'
+  	# echo "!!!!!"
+  	echo $endSubstring
+  	echo "+++++++++++++++++++++++++++++++++++++++++++++"
+    echo "$line" | cut -b 2-$endSubstring
+  fi
+  echo ""
+  echo "Please  fix the above errors"
+done < "$input"
+
+
+# if [[ "$file" == *"<error"* ]]; then
+#   echo "There are linting errors. Please check the report (target/site/checkstyle.html)"
+#   echo
+#   exit 1
+# else
+#   echo "No linting errors"
+#   echo
+#   exit 0
+# fi
